version: '3.4'

services:
  db:
    container_name: mysql_container
    image: mysql:5.7
    build: ./db
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: root
      MYSQL_DATABASE: events-around-me
      DATABASE_HOST: db
  redis-server: 
    image: 'redis'
  node-app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: events-around-me
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "4000:4000"